# Configure main menu and social menu


[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/youyin-hu-a7888b1b6"

    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:youyinhu6@gmail.com"

    [social.params]
        icon = "mail"
